"""Unofficial high-throughput Cohere Arabic/English batch transcription."""

from ._version import __version__
from .api import Transcriber, transcribe
from .api.types import (
    AudioInput,
    BatchTranscriptionError,
    Language,
    OutputFormat,
    ProgressCallback,
    ProgressCallbackError,
    ProgressEvent,
    PublicationOptions,
    ResultStatus,
    SubtitleCue,
    TranscriberBusyError,
    TranscriberClosedError,
    TranscriptionConfigurationError,
    TranscriptionError,
    TranscriptionInputError,
    TranscriptionOptions,
    TranscriptionProvenance,
    TranscriptionResult,
    TranscriptionRun,
    TranscriptionRuntimeError,
    TranscriptionSegment,
    TranscriptionStatistics,
    TranscriptionWord,
)

__all__ = [
    "AudioInput",
    "BatchTranscriptionError",
    "Language",
    "OutputFormat",
    "ProgressCallback",
    "ProgressCallbackError",
    "ProgressEvent",
    "PublicationOptions",
    "ResultStatus",
    "SubtitleCue",
    "Transcriber",
    "TranscriberBusyError",
    "TranscriberClosedError",
    "TranscriptionConfigurationError",
    "TranscriptionError",
    "TranscriptionInputError",
    "TranscriptionOptions",
    "TranscriptionProvenance",
    "TranscriptionResult",
    "TranscriptionRun",
    "TranscriptionRuntimeError",
    "TranscriptionSegment",
    "TranscriptionStatistics",
    "TranscriptionWord",
    "__version__",
    "transcribe",
]
